### ISSUE TITLE
Running on Windows to Send to Arduino

### ISSUE THREAD

**Issue by ItzTeeAye** [sparkfun/Qwiic_SCMD_Py#2]
I'm working on a project that has python running on a windows machine, sending commands to Arduino Uno via bluetooth with the HC-05. The arduino is running firmata Express, and I'm using Pymata4 to send the commands. But we have a Qwiic Motor Driver connected to the Uno that we are trying to control, am I able to use this library? I got it to run by modifying a couple things to work on Windows, but in Python, when it connects to the Uno, it says that it doesn't find the motor driver.

**Comment by santaimpersonator** [comment]
I will be closing this issue for several reasons:

- It looks like this has issue has been sitting for a while.
- This appears to be a technical assistance question, which should be posted on [our forum](https://forum.sparkfun.com/).
     - Please refer to our [hookup guide](https://learn.sparkfun.com/tutorials/hookup-guide-for-the-qwiic-motor-driver) for how to get started with the Qwiic motor driver.
- This issue has nothing to do with this Python package.

To answer your question... no, you cannot use this package to interface with your Arduino board from your computer. You should be using the Arduino IDE to do that. As mentioned in the, `README.md` of this repository... Windows is not supported:
![image](https://github.com/sparkfun/Qwiic_SCMD_Py/assets/36016723/b3030375-1f3d-4aa2-b7b3-0c78c1b83678)

The `README.md`, also mentions the Arduino library that this Python package was ported from:
![image](https://github.com/sparkfun/Qwiic_SCMD_Py/assets/36016723/9ad25c7a-a326-4ebf-8865-dc287b8ca985)

- Please refer to the [hookup guide](https://learn.sparkfun.com/tutorials/hookup-guide-for-the-qwiic-motor-driver#software-setup) for utilizing that [Serial Controlled Motor Driver Arduino library](https://github.com/sparkfun/SparkFun_Serial_Controlled_Motor_Driver_Arduino_Library), to interface with the Arduino board from the Arduino IDE... and operate the Qwiic Motor Driver from your Windows computer.
